### PR TITLE
Remove default NET, use port forward

### PR DESCRIPTION
**Pull request by iShift**
change default port to 8433 for easy documenting where change port..

### CODE REVIEW

**Comment by alexbers** [comment]
This looks good, but I'd like to keep the current solution because many people use the proxy without docker and set the port in the config.py. Current solution provides the same way to set the port in both cases: with docker and without it. Also the proposed solution add one more magic number: 8443 in addition to 3256

**Comment by iShift** [comment]
ok, maybe change port from 8443 (i chose them because often it is in white lite like 443/80) to standard that you chose ? (main idea of PR is replace NET to port forwarding)

**Comment by iShift** [comment]
also interesting, with config file i can't bind proxy using docker to 443 port =)

**Comment by alexbers** [comment]
only root can use ports <1024, please, try to change user to root in the Dockerfile

**Pull request closed without merging**
