### PR TITLE
Added quota usage management

### PR DESCRIPTION
**Pull request by HirbodBehnam**
## What is this?
This is a small pull request to add an option to proxy to limit the data usage of users. 
### How it works?
The proxy logs how many bytes has been transferred in `stats[user]["octets"]`. I used this info to setup a limiter. If the limit is reached, all new connections will be dropped. 
#### How do you save stats?
Good question. The `stats[user]["octets"]` for limited users must be saved somewhere. So my idea was this: Everytime the proxy prints the stats, also resave the `DATA_QUOTA` with the _remaining_ amount of data quota. For example if the limit is 2000 bytes (`DATA_QUOTA = {'tg': 2000}`) and user consume 1500 bytes, after the info is shown, the config file must be changed to `DATA_QUOTA = {'tg': 500}`
I know it is not the best way to do it but that's the best I can do. (sorry)
#### What options are added to config?
* `DATA_QUOTA`: It is used to tell the proxy what users have limits and how much. It is used like `USER_MAX_TCP_CONNS` and the number assigned to the users is the quota in bytes.  See below for example. 
* `AGGRESSIVE_DATA_QUOTA`: (Boolean) If true, proxy will immediately drop all active connections of the target user. Otherwise, the proxy will drop all new incoming connections. In other words, if disabled, if a user reaches its max quota, he is able to send messages(only text) until he/she closes the Telegram.
### Have you tested this?
Yes but not alot. Just like added the limiter and watching the connections drop.
### Example of config file?
```python
# Other configs
USERS = {
    "tg":  "00000000000000000000000000000000",
    "tg2": "10000000000000000000000000000000"
}
DATA_QUOTA = {'tg': 1024*1024*50}
# The tg user is limited to 50mb of data transfer; However tg2 is not limited at all
AGGRESSIVE_DATA_QUOTA = True
```

Also the code quality is very bad. (Especially in the config saver) This is my first ever python project so you may need to review the code first :)

If you have any questions do not hesitate to comment on the code and ask what is this.

### CODE REVIEW

**Comment by alexbers** [comment]
Hello, could you please describe why do you need such byte quota limits?

**Comment by HirbodBehnam** [comment]
I don't need it. Somebody contacted me in Telegram and asked if it is possible or not. I said it is but you need to change the code of the proxy.
They were trying to sell private proxies and they wanted to limit the data clients can use. (They said something like shadowsocks manager)
+ That was a good python practice for me.

BTW: If you like I can remove the aggressive data quote option. (I think this one is useless)

**Comment by alexbers** [comment]
I've implemented the basic quotas. https://github.com/alexbers/mtprotoproxy/commit/985e3eb546777078d89bc87cb0da1f362b566f98. Thank you.

The usage saving functionality add a state to the proxy. It is a big price for the feature that are needed mostly by those who sell access. Also they still need some infrastructure to answer the clients' questions about how much data is left and why the proxy doesn't work (is it because of quotas). Also they need to integrate them with payment systems, etc.

Also the code has many issues: from editing the config of itself to saving a data in the function named stats_printer.

**Comment by HirbodBehnam** [comment]
That's ok thanks.
I also just realized that can also edit config with sending `SIGUSR2` to proxy and that does not reset the statics. That's good because sellers can use it to keep the size of data that users have used.

**Comment by pouryare** [comment]
Is it possible to set remaining quotas to config file just when the program receives a `SIGKILL` or `SIGUSR2` signal?

**Comment by HirbodBehnam** [comment]
I think so because the quotas will be reloaded too.

**Pull request closed without merging**
