### PR TITLE
Use environment variables for the script configuration (easy launch in a container environment)

### PR DESCRIPTION
**Pull request by beshkenadze**
Here is my idea of how to improve launch in one command line as a docker image (in my repo https://github.com/beshkenadze/mtprotoproxy you can see how it builds as a docker image).
This PR doesn't change the main flow of usage and just add a small feature: user environment variables for the script configuration.

P.S. I'm not very good at Python; maybe there is a better way to do that.

### CODE REVIEW

**Comment by alexbers** [comment]
Thanks for the pull request.

The proxy already has the undocumented way of launching, which allows to specify port, secret, ad_tag and tls_domain with command line arguments:

```
python3 mtprotoproxy.py 1234 00000000000000000000000000000001 3c09c680b76ee91a4c25ad51f742267d test.com
```

or even (without docker-compose):
```
docker run alexbers/mtprotoproxy python3 mtprotoproxy.py 1234 00000000000000000000000000000001 3c09c680b76ee91a4c25ad51f742267d test.com
```

Also these arguments can be specified in the docker-compose.yml with *command* option, which should meet your goals.

I see several issues in this pull request:
1) (the main one) it breaks backward compatibility. The proxy will stop to work after updating until the user transfer the config options from config.py to environments docker-compose.yml
2) the proxy has a functionality to reload config if it got SIGUSR2 signal. Some users asked me to add it to dynamically adjust user limits or add users without restarting the proxy. With environment variables this function will be lost
3) the proxy configuration was contained in just one place - the config.py, now it contained in two different places which is less clear for the new users. New files are appeared: env.py, docker-compose-dev.yml and .gitignore. The users will have to understand the difference between docker-compose-dev.yml and docker-compose.yml and purpose of env.py
4) only restricted set of options can be passed using the environment variables. The proxy has few dozens of fine tuning options which will be impossible to set with bundled env.py

Could you please explain your use case a little more: why do you want to settings be passed using the environment vars specified in docker-compose.yml instead of config.py? May be I can come to something which will meet your goals without breaking the backward compatibility

**Comment by beshkenadze** [comment]
1. The PR shouldn't break backward compatibility you can check with my last image docker run beshkenadze/mtprotoproxy python3 mtprotoproxy.py 1234 00000000000000000000000000000001 3c09c680b76ee91a4c25ad51f742267d test.com
2. The same problem and with the config.py, isn't it?
3. IMHO, the better way to store a configuration in the environment because it is the universal method in the many systems also can use with dotenv for storing in the .env file. 
About docker-compose files: You copy source files twice: in docker-compose.yml and Dockefile, IMHO, it's useless for end-user, but for development, it uses. So, that's why I decide to split the docker-compose file.
4. Here is lack of documentation of restricted options :(

**Comment by alexbers** [comment]
1. If user with docker updates the proxy version the config variables will be taken from env.py instead of config.py, so if user had customized config.py, the settings will be lost
2. The config.py is mapped into the container as volume, so if it is changes on the host, it also changes in the container
3. I checked the few random docker containers I use to determine how the config is passed inside the container:
- nginx: by mapping config file for complex configs, by environment for simple configs
- httpd: by putting the config file inside the container
- postgres: by copying configuration scripts for complex config, command line args for simpler configs and by environment for basic config
- mariadb: by mapping config file for complex configs, by command line args for custom config options or by environment for basic config

None of the containers I looked at use the environment variables as the only way of configuration. I think this is possible only with the software which have just a few options to configure. What I am trying to understand is why the environment variables are better than command line arguments: instead of installing and use dotenv it is possible to just add some args in the end of command. With dotenv it still needed to add the dotenv command as zeroth arg. The only case I know is to make a secret invisible for other users of this server. But this can happen only on shared servers and to run docker the user have to be root.

The source files are copied once and for the second time they are mapped. This allows the dynamic reconfiguration to work, and also makes possible to use the container directly, without mappings. As far I know, this is a common strategy to have a default config and a possibility to override it using mappings.

The configuration using the python script is non-standard but it is the most universal way I know: it allows to just enumerate options in the config file as usual, generate them using Python code (e.g. get from some server) or use json and pyyaml modules for load the configs in the another format. Also it allows to get the options from the config variables.

Now I am thinking about adding a logic to the proxy: if some environment variable are founded (e.g. PORT or SECRET) - to apply it as the config option. I trying to find use cases where it will be more convenient than command line options.

**Comment by beshkenadze** [comment]
Anyway, I didn't know about passing parameters through arguments. I close the PR for now.

**Pull request closed without merging**
